name: Deploy on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release source
        uses: actions/checkout@v3

      - name: Deploy to CyberPanel (VPS)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/DOMAIN/public_html   # path project di CyberPanel
            git fetch --tags
            git checkout ${{ github.event.release.tag_name }} -f
            composer install --no-dev --optimize-autoloader
            php spark cache:clear
